runtime: nodejs18

env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 32

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301